# Use the latest Ubuntu as the base image
FROM ubuntu:latest

# Update APT package manager
RUN apt-get update

# Upgrade currently installed software
RUN apt-get upgrade -y

# Set the default command to echo "Hello, World!"
CMD ["echo", "Hello, World!"]
